[package]
name = "slack-it-to-me"
version = "0.1.0"
edition = "2018"
authors = ["Alex Afshar <contact@alexafshar.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11"
clap = "2.33.3"
